version: "3.8"

services:
 
  app:
    build: .
    container_name: api-gateway
    ports:
      - "4004:4004"
    environment:
      AUTH_SERVICE_URL: http://auth-service-app:4005
      
    networks:
      - internal

    volumes:
      - .:/app
networks:
  internal:
    external: true