server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## http://localhost:4004/auth/login
            ## Will be passed to http://auth-service-app:4005
            ## As predicates matched
            - id: auth-service-route
              uri: http://auth-service-app:4005l
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: patient-service-route
              uri: http://patient-service-app:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
                - JwtValidation  ## JwtValidationGatewayFilterFactory , follow naming convention