version: "3.8"

services:
  db:
    image: postgres

    container_name: auth-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: postgres
    ports:
      - "5001:5432"
    networks:
      - internal
    volumes:
      - D:\JAVA_FULL_STACK_PROJECTS\Auth-Service-DB-Volume:/var/lib/postgresql 


  app:
    build: .
    container_name: auth-service-app
    ports:
      - "4005:4005"
    networks:
      - internal
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: YuGsM7f6uU7smIp1ow65IIzGog4ZInnVTo2QkjhvULS

    volumes:
      - .:/app
    depends_on:
      - db
networks:
  internal:
    external: true